### PR TITLE
workflow-metrics-orphaned-indices-2

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@MarinhoFeliphe I had to abort the `relevant` test because it froze in CI

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:stable

**Pull request closed without merging**
